# Generated by Django 2.1 on 2019-11-14 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191028_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('timeofleave', models.TimeField()),
                ('dateofleave', models.DateField(null=True)),
                ('price', models.CharField(max_length=120)),
                ('seats', models.CharField(max_length=120)),
                ('anything', models.CharField(max_length=120)),
                ('email', models.ForeignKey(default='doenteremail@gmail.com', on_delete=django.db.models.deletion.SET_DEFAULT, to='home.Register')),
            ],
        ),
    ]
