# Generated by Django 2.1 on 2019-11-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191115_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_email', models.CharField(max_length=120)),
                ('offer_email', models.CharField(max_length=120)),
                ('source', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('timeofleave', models.TimeField()),
                ('dateofleave', models.DateField(null=True)),
                ('price', models.CharField(max_length=120)),
                ('seats', models.CharField(max_length=120)),
                ('anything', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_email', models.CharField(max_length=120)),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('passenger_email', models.CharField(max_length=120)),
                ('phonenumber', models.CharField(max_length=120)),
            ],
        ),
    ]
