# Generated by Django 2.1 on 2019-11-20 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191119_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cleared',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
