# Generated by Django 2.1 on 2019-11-20 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_notification_cleared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='password',
        ),
    ]
