# Generated by Django 2.1 on 2019-11-21 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_booking_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='phonenumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
